spring:
  datasource:
    initialization-mode: always
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  banner:
    charset: UTF-8
    location: classpath:banner.txt


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
