CREATE TABLE genres(
id INT PRIMARY KEY AUTO_INCREMENT,
  name_genre VARCHAR(50) NOT NULL);

CREATE TABLE authors(
id INT PRIMARY KEY AUTO_INCREMENT,
genres_id INT,
name_author VARCHAR(50) NOT NULL,
FOREIGN KEY (genres_id) REFERENCES genres(id));

CREATE TABLE books(
id INT PRIMARY KEY AUTO_INCREMENT,
authors_id INT REFERENCES authors(id),
name_book VARCHAR(50) NOT NULL);


