CREATE TABLE genres
(id INT PRIMARY KEY AUTO_INCREMENT , nameGenre VARCHAR(50) NOT NULL);

CREATE TABLE authors
(id INT PRIMARY KEY AUTO_INCREMENT,genresId INT, nameAuthor VARCHAR(50) NOT NULL, FOREIGN KEY (genresId) REFERENCES genres(id));

CREATE TABLE books
 (id INT PRIMARY KEY AUTO_INCREMENT, authorsId INT, nameBook VARCHAR(50) NOT NULL, FOREIGN KEY (authorsId) REFERENCES authors(id));
